/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * To learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.5/samples
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    kotlin("jvm") version "1.9.20"
    application
}
repositories {
    mavenCentral()
}
application {
    // mainClass.set("HelloWorldKt")
    // mainClass.set("MyIfElseKt")
    mainClass.set("VarianceKt")
}